### ISSUE TITLE
Please add `vedantmgoyal2009[bot]` to approvedBots

### ISSUE THREAD

**Issue by vedantmgoyal9** [microsoft/cla-approved-bots#2]
Hello there,

I use my bot account to commit changes to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) repository. Source code of the bot can be found here: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/Automation.ps1

@JohannesLampel @DragosDanielBoia Please tell if I can make a PR to add my bot as well.

**Comment by DragosDanielBoia** [comment]
@vedantmgoyal2009 go ahead, will approve and merge it.

**Comment by vedantmgoyal9** [comment]
@DragosDanielBoia PR opened 👍🏻
